/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kkishore' at '7/25/16 7:33 AM' with Gradle 2.9
 *
 * @author kkishore, @date 7/25/16 7:33 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
